<<<<<<<< HEAD:drivers/misc/mediatek/imgsensor/src/mt6765/camera_hw/Makefile
#
# Copyright (C) 2017 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

#
# Makefile for misc devices that really don't fit anywhere else.
#
ccflags-y += -I$(MTK_CUSTOM_PATH)/imgsensor/inc \

obj-y		+= regulator/
obj-y		+= gpio/
obj-y		+= mclk/
obj-y		+= imgsensor_cfg_table.o
========
#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += dsi_panel_c3u_46_0f_0c_dsc_vdo.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
>>>>>>>> 7f92d5f16c64 (gale: drivers: misc: mediatek: lcm: Import Xiaomi changes):drivers/misc/mediatek/lcm/dsi_panel_c3u_46_0f_0c_dsc_vdo/Makefile
